services:
  - type: web
    name: tkea237-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: node app.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
